# Generated by Django 4.1.2 on 2022-10-28 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='Состояние',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='Время',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 20, 45, 47, 62258)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='Последнее использование',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 20, 45, 47, 63248)),
        ),
    ]
