# Generated by Django 4.1.2 on 2022-10-28 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_tags_состояние_alter_history_время_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Адрес метки',
            new_name='Адрес_метки',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='Адрес метки',
            new_name='Адрес_метки',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='Количество использований',
            new_name='Количество_использований',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='Последнее использование',
        ),
        migrations.AddField(
            model_name='tags',
            name='Последнее_использование',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 21, 3, 14, 860571)),
        ),
        migrations.AlterField(
            model_name='history',
            name='Время',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 21, 3, 14, 860571)),
        ),
    ]
